#!/bin/sh /etc/rc.common

LOCK=/var/lock/netwizard-boot.lock
START=99
UCISET='uci -q set'
UCIDEL='uci -q delete'
boot() {
	XBOOT=1 start
}

setipv6() {
	case $1 in
		0) 
			$UCIDEL network.wan6
			$UCISET dhcp.lan.ra=''
			$UCISET dhcp.lan.dhcpv6=''
			$UCISET dhcp.lan.ndp=''
			$UCISET dhcp.@dnsmasq[0].filter_aaaa="1"
			$UCISET dhcp.lan.force='1'
			$UCIDEL dhcp.lan.ignore
			$UCIDEL dhcp.lan.ra
			$UCIDEL dhcp.lan.ra_default
			$UCIDEL dhcp.lan.ra_slaac
			$UCIDEL dhcp.lan.dhcpv6
			$UCIDEL dhcp.lan.ra_flags
			$UCIDEL dhcp.wan.ra
			$UCIDEL dhcp.wan.ndp
			$UCIDEL dhcp.wan.ra_flags
			$UCIDEL dhcp.lan.dns
			uci add_list dhcp.wan.ra_flags='none'
			$UCISET network.lan.delegate='0'
			$UCISET network.wan.ipv6='0'
			$UCISET network.wan.delegate='0'
			# $UCIDEL network.globals.ula_prefix
		;;
		1)
			$UCISET dhcp.lan.ra='server'
			$UCISET dhcp.lan.dhcpv6='server'
			$UCIDEL dhcp.@dnsmasq[0].filter_aaaa
			$UCISET dhcp.lan.ndp='relay'
			$UCISET dhcp.lan.ra_management='1'
			$UCISET dhcp.lan.ra_default='1'
			$UCISET dhcp.lan.force='1'
			$UCIDEL dhcp.lan.ra_flags
			$UCISET dhcp.wan.master='1'
			$UCISET network.wan.ipv6='auto'
			$UCISET network.lan.delegate='0'
			$UCISET network.wan.delegate='0'
			$UCISET network.wan6.delegate='0'
			$UCIDEL network.wan6.reqaddress='try'
			$UCISET network.wan6.reqprefix='auto'
			$UCIDEL firewall.@zone[1].network
			uci add_list firewall.@zone[1].network='wan'
			uci add_list firewall.@zone[1].network='wan6'

		;;
		2)
			$UCISET dhcp.lan.ra='relay'
			$UCISET dhcp.lan.dhcpv6='relay'
			$UCISET dhcp.lan.ndp='relay'
			$UCIDEL dhcp.@dnsmasq[0].filter_aaaa
			$UCISET dhcp.lan.ndp=''
			$UCISET dhcp.lan.ra_management='1'
			$UCISET dhcp.lan.ra_default='1'
			$UCISET dhcp.lan.force='1'
			$UCISET network.lan.delegate='0'
			$UCISET network.lan.ip6assign='64'
			$UCISET dhcp.lan.master='1'
		;;
		3)
			$UCISET dhcp.lan.ra='hybrid'
			$UCISET dhcp.lan.dhcpv6='hybrid'
			$UCISET dhcp.lan.ndp='hybrid'
			$UCIDEL dhcp.@dnsmasq[0].filter_aaaa
			$UCISET dhcp.lan.ndp=''
			$UCISET dhcp.lan.ra_management='1'
			$UCISET dhcp.lan.ra_default='1'
			$UCISET dhcp.lan.force='1'
			$UCISET dhcp.wan.master='1'
			$UCIDEL dhcp.wan.ra_flags
			$UCISET dhcp.wan.ra='hybrid'
			$UCISET dhcp.wan.dhcpv6='hybrid'
			$UCISET dhcp.wan.ndp='hybrid'
			uci add_list dhcp.wan.ra_flags='none'
			$UCISET network.wan.ipv6='auto'
			$UCISET network.wan.delegate='0'
			$UCISET network.lan.delegate='0'
			$UCISET network.wan6.delegate=0
			$UCISET network.lan.ip6assign='64'
			$UCISET network.wan6.$ifname="@wan"
			$UCISET network.wan6.reqaddress=try
			$UCISET network.wan6.reqprefix=auto
			$UCIDEL firewall.@zone[1].network
			uci add_list firewall.@zone[1].network='wan'
			uci add_list firewall.@zone[1].network='wan6'
		;;
	esac
}
add_netwizard() {
	local cfg="$1"
	local wan_proto wan_ipaddr wan_netmask wan_gateway wan_dns wan_pppoe_user wan_pppoe_pass 
	local ipv6 wifi_ssid wifi_key old_wifi_ssid old_wifi_key showhide
	local lan_ipaddr lan_netmask lan_gateway lan_dns lan_dhcp wan_interface
	local ifname lannet a b i
 	config_get showhide "$cfg" showhide '0'
	config_get wan_proto "$cfg" wan_proto 'dhcp'
	config_get ipv6 "$cfg" ipv6 '0'
	config_get dnsset "$cfg" dnsset '223.5.5.5'
	config_get wan_interface "$cfg" wan_interface 'eth1'
	config_get lan_dhcp "$cfg" lan_dhcp '0'
	config_get synflood "$cfg" synflood '0'
	config_get redirectdns "$cfg" redirectdns '0'
	config_get lan_ipaddr "$cfg" lan_ipaddr `uci -q get network.lan.ipaddr`
	config_get lan_netmask "$cfg" lan_netmask '255.255.255.0'
	config_get dns_tables "$cfg" dns_tables 'iptables -t nat -I POSTROUTING -o br-lan -j MASQUERADE'
 	if [ "x$showhide" = "x1" ] ; then
 		 touch /etc/config/netwizard_hide 
		 $UCISET advancedplus.@basic[0].wizard="1"
		 uci commit advancedplus
 		 exit
 	else
	         rm -rf  /etc/config/netwizard_hide
		 $UCISET advancedplus.@basic[0].wizard="0"
		 uci commit advancedplus
	fi
 	touch $LOCK
	ifname=$(uci -q get network.lan.ifname ) 
	[ "x$ifname" = "x" ] && ifname="device" || ifname="ifname" 
 	[ -n "$wan_interface" ] || wan_interface=$(uci -q get network.wan.$ifname 2>/dev/null) 
 	$UCIDEL network.lan.gateway
	$UCIDEL dhcp.lan.ignore
	$UCIDEL network.lan.dns
	$UCIDEL firewall.@zone[0].masq
	[ `uci -q get network.wan` ] && $UCIDEL network.wan
	[ `uci -q get network.wan6` ] && $UCIDEL network.wan6
	[ `uci -q get network.lan6` ] && $UCIDEL network.lan6
	$UCISET network.wan=interface
	$UCISET network.wan6=interface
	$UCISET network.wan6.proto='dhcpv6'
	$UCISET network.wan6.delegate='1'
	$UCIDEL dhcp.wan.master
	$UCIDEL dhcp.lan.master
	uci -q add_list dhcp.lan.dns="2400:3200::1"
	uci -q add_list dhcp.lan.dns="240C::6666"
	sed -i '/j MASQUERADE/d' /etc/firewall.user
	a=$(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' )
	b=$(echo "$a" | wc -l)
	[ ${b} -gt 1 ] && {
	  lannet=""
	  for i in $(seq 1 $b) ; do [ "${wan_interface}" = "$(echo "$a" | sed -n ${i}p)" ] || lannet="${lannet} $(echo "$a" | sed -n ${i}p)" ;done
 	  [ "x$ifname" = "xdevice" ] &&  $UCISET network.@$ifname[0].ports="${lannet}"  || $UCISET network.lan.$ifname="${lannet}"
	}
	$UCISET network.wan.$ifname="${wan_interface}"
	$UCISET network.wan6.$ifname="${wan_interface}"
 	case "${wan_proto}" in
		dhcp)
			$UCISET network.wan.proto='dhcp'
			#$UCISET network.wan.metric='40'
			$UCISET network.wan.delegate='0'
			[ "x$ipv6" = "x1" ] && setipv6 3 || setipv6 0
		;;
		static)
			config_get wan_ipaddr "$cfg" wan_ipaddr
			config_get wan_netmask "$cfg" wan_netmask
			config_get wan_gateway "$cfg" wan_gateway
			
			[ "x$ipv6" = "x1" ] && setipv6 3 || setipv6 0
			test -n "${wan_ipaddr}" && test -n "${wan_netmask}" && {
				$UCISET network.wan.proto='static'
				#$UCISET network.wan.metric='40'
				$UCISET network.wan.ipaddr="${wan_ipaddr}"
				$UCISET network.wan.netmask="${wan_netmask}"
				$UCISET network.wan.gateway="${wan_gateway}"
				config_get wan_dns "$cfg" wan_dns
				test -n "${wan_dns}" && {
					uci set network.wan.peerdns='0'
					uci set network.wan.dns="${wan_dns}"
				}
			}
		;;
		pppoe)
			config_get wan_pppoe_user "$cfg" wan_pppoe_user
			config_get wan_pppoe_pass "$cfg" wan_pppoe_pass
			[ "x$ipv6" = "x1" ] && setipv6 1 || setipv6 0
			[[ "${wan_pppoe_user} != $(uci get network.wan.username)" || "${wan_pppoe_pass} != $(uci get network.wan.password)" ]] && {
				$UCISET network.wan.proto='pppoe'
				#$UCISET network.wan.metric='40'
				$UCISET network.wan.username="${wan_pppoe_user}"
				$UCISET network.wan.password="${wan_pppoe_pass}"
				$UCISET network.wan.keepalive='60 60'
				$UCISET network.wan.mtu='1420'
				config_get wan_dns "$cfg" wan_dns
				test -n "${wan_dns}" && {
					$UCISET network.wan.peerdns='0'
					$UCISET network.wan.dns="${wan_dns}"
				}
			}
		;;
		siderouter)
			config_get lan_gateway "$cfg" lan_gateway
			config_get lan_dns "$cfg" lan_dns
			config_get lan_snat "$cfg" lan_snat
			config_get masq "$cfg" masq
			config_get snat_tables "$cfg" snat_tables
			test -n "${lan_gateway}" && {
				$UCISET network.lan.gateway="${lan_gateway}"
				[ -n "$lan_dns" ] || lan_dns='223.5.5.5'
				$UCISET network.lan.dns="${lan_dns}"
					if [ ${b} -gt 1 ] ; then
					     [ "x$ifname" = "xdevice" ] &&  $UCISET network.@$ifname[0].ports="${lannet} ${wan_interface}"  || $UCISET network.lan.$ifname="${lannet} ${wan_interface}"
					fi
				[ "x$masq" = "x1" ] && $UCISET firewall.@zone[0].masq='1' || $UCIDEL firewall.@zone[0].masq
				[ "x$lan_snat" = "x1" ] && echo "${snat_tables}" >> /etc/firewall.user 
			}
			$UCIDEL firewall.@zone[0].network
			uci add_list firewall.@zone[0].network='lan'
			[  `uci show network  | grep utun | wc -l ` -gt 1 ] && uci add_list firewall.@zone[0].network='utun'
			[ "x$ipv6" = "x1" ] && {
			      	setipv6 2
			      	$UCISET network.lan6=interface
			      	$UCISET network.lan6.proto='dhcpv6'
			      	$UCISET network.lan6.delegate='1'
				$UCISET network.lan6.$ifname="@lan"
				# $UCISET firewall.@zone[0].network='lan lan6'
				uci add_list firewall.@zone[0].network='lan6'
			} || {
				setipv6 0
			}
			[ `uci get network.wan` ] && $UCIDEL network.wan
			[ `uci get network.wan6` ] && $UCIDEL network.wan6
			$UCIDEL firewall.@zone[1].network
		;;		
	esac
	test -n "${lan_ipaddr}" && test -n "${lan_netmask}" && {
		$UCISET network.lan.ipaddr="${lan_ipaddr}"
		$UCISET network.lan.netmask="${lan_netmask}"
	}
	[ "x$redirectdns" = "x1" ] && {
        	echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
        	echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
        	echo "[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
        	echo "[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
	} || sed -i '/--dport 53 -j REDIRECT --to-ports 53/d' /etc/firewall.user
	[ "x$synflood" = "x1" ] && $UCISET firewall.@defaults[0].syn_flood='1' || $UCIDEL firewall.@defaults[0].syn_flood
	sed -i "/dhcp_option '6/d" /etc/config/dhcp
	sed -i "/list dns/d" /etc/config/dhcp
	if [ "x$lan_dhcp" = "x0" ] ; then 
	    # $UCISET dhcp.lan.dynamicdhcp="1" 
	    $UCISET dhcp.lan.ignore="0" 
	    [ "x$dnsset" = "x1" ] && {
	          [ "${dns_tables}" = "1" ] && uci -q add_list dhcp.lan.dhcp_option="6,${lan_ipaddr}" || uci -q add_list dhcp.lan.dhcp_option="6,${dns_tables}" 
	    }
	else
	    # $UCISET dhcp.lan.dynamicdhcp="0" 
	    $UCISET dhcp.lan.ignore="1"
	fi
	wifi_setup_radio(){
	local radio=$1
	uci get wireless.${radio} >/dev/null 2>&1 && {
		if [ "$(uci get wireless.${radio}.band)" = "5g" ]; then
			$UCISET wireless.default_${radio}.ssid="${wifi_ssid}_5G"
		else
			$UCISET wireless.default_${radio}.ssid="${wifi_ssid}_2.4G"
		fi
			$UCISET wireless.default_${radio}.device="${radio}"
			if [ "${wifi_key}" ]; then
				$UCISET wireless.default_${radio}.encryption='psk2'
				$UCISET wireless.default_${radio}.key="${wifi_key}"
			else
				$UCISET wireless.default_${radio}.encryption='none'
			fi
		}
	}
	config_get wifi_ssid "$cfg" wifi_ssid
	config_get wifi_key "$cfg" wifi_key
	config_get old_wifi_ssid "$cfg" old_wifi_ssid
	config_get old_wifi_key "$cfg" old_wifi_key
	test -n "${wifi_ssid}" && test -n "${wifi_key}" && {
		for idx in `seq 0 64`; do
			uci get wireless.@wifi-iface[$idx] 2>/dev/null || break
			[ "$(uci get wireless.@wifi-iface[$idx].mode 2>/dev/null)" = "ap" ] && {
				$UCISET wireless.@wifi-iface[$idx].ssid="${wifi_ssid}"
				$UCISET wireless.@wifi-iface[$idx].key="${wifi_key}"
				$UCISET wireless.@wifi-iface[$idx].encryption='psk2'
			}
		done
	}
	if [[ "${wifi_ssid}" != "${old_wifi_ssid}" || "${wifi_key}" != "${old_wifi_key}" ]]; then
 	 	test -n "${wifi_ssid}" && {
		for radio in radio0 radio1 radio2 radio3; do
			wifi_setup_radio ${radio}
		done
		uci commit wireless
	 	}

 		$UCISET netwizard.default.old_wifi_ssid="${wifi_ssid}"
	 	$UCISET netwizard.default.old_wifi_key="${wifi_ssid}"
	fi
	uci commit netwizard
	uci commit dhcp
	uci commit firewall
	uci commit network
	(sleep 2
	 /etc/init.d/network restart
	 /etc/init.d/dnsmasq reload)&
}

start() { 
	[ -f $LOCK ] && exit
	[ "x$XBOOT" = "x1" ] && exit 0
	config_load netwizard
	config_foreach add_netwizard netwizard
	rm -f $LOCK 2>/dev/null
}

stop() {
	rm -f $LOCK 2>/dev/null
}