#
# Copyright (C) 2020 OpenWrt.org
# 流量统计
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Wrtbwmon-pd
PKG_NAME:=luci-app-wrtbwmon-pd
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=7
LUCI_DEPENDS:=+wrtbwmon

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

