#!/bin/sh /etc/rc.common
START=90
USE_PROCD=1
n=zerotier
p=/var/lib/$n-one

gen(){
	echo '#!/bin/sh' > /var/etc/$n.include
}

flush(){
	eval $(iptables-save -t $1 | grep $n | sed -e 's/^-A/iptables -t $1 -D/' -e 's/$/;/')
}

start_instance(){
	gen
	[ "$(uci -q get $n.$1.enable)" = 1 ] || return 1
	config_get port $1 port
	config_get secret $1 secret
	mkdir -p $p/networks.d
	if [ ! $secret ];then
		secret=$($n-idtool generate) || return 1
		uci set $n.$1.secret=$secret
		uci commit $n
	fi
	[ $secret ] && echo "$secret" > $p/identity.secret
	for i in $(uci -q get $n.$1.join);do
		touch $p/networks.d/$i.conf
	done
	procd_open_instance
	procd_set_param command /usr/bin/$n-one $([ $port ] && echo "-p$port") $p
	procd_set_param stderr 1
	procd_close_instance
	/usr/share/zerotier/nat up &
}

service_triggers(){
	procd_add_reload_trigger $n
}

start_service(){
	config_load $n
	config_foreach start_instance $n
}

stop_service(){
	rm -rf $p
	gen
	flush filter
	flush nat
}

reload_service(){
	stop
	start
}
