#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ddnsto[-1]
	add ucitrack ddnsto
	set ucitrack.@ddnsto[-1].init=ddnsto
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
