#!/bin/sh
touch /etc/config/ddnsto
# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@ddnsto[-1]
	add ucitrack ddnsto
	set ucitrack.@dnsto[-1].init=ddnsto
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
