#!/bin/sh
touch /etc/config/dnsto
# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@dnsto[-1]
	add ucitrack dnsto
	set ucitrack.@dnsto[-1].init=dnsto
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
