#!/bin/sh /etc/rc.common
START=50

run_poweroff()
{
	local minute
	local hour
	config_get week $1 week
	config_get minute $1 minute
	config_get hour $1 hour
    if [ $minute = 0 ] ; then
           minute="00"
	fi
    if [ $week = 7 ] ; then
           week="*"
	fi
		
	local cmd="$minute $hour * * $week sleep 5 && touch /etc/banner && poweroff" 
	if [ ! -f "/etc/crontabs/root" ] || [ $(cat /etc/crontabs/root | grep "$cmd" | wc -l) -eq 0 ]; then
			sed -i '/poweroff/d' /etc/crontabs/root >/dev/null 2>&1
			echo "$cmd" >> /etc/crontabs/root
	fi
}

start()
{
	local enabled=$(uci get autopoweroff.@global[0].enabled)
	[ "$enabled" -eq 0 ] && exit
	config_load autopoweroff
	config_foreach run_poweroff autopoweroff
}

del_cru()
{
	if [ -f "/etc/crontabs/root" ] && [ $(cat /etc/crontabs/root | grep poweroff | wc -l) -ne 0 ]; then
		sed -i '/poweroff/d' /etc/crontabs/root >/dev/null 2>&1
	fi
}

stop() {
	del_cru
}

reload(){
	stop
	start
}