#!/bin/sh /etc/rc.common
START=50

run_poweroff()
{
	local enable
	config_get_bool enable $1 enable

	local minute
	local hour
	config_get dstype $1 dstype
	config_get week $1 week
	config_get minute $1 minute
	config_get hour $1 hour
	
    if [ $minute = 0 ] ; then
           minute="00"
	fi
    if [ $week = 7 ] ; then
           week="*"
	fi
    if [ $dstype = 0 ] ; then
		local cmd="$minute $hour * * $week sleep 5 && touch /etc/banner && reboot" 
		if [ ! -f "/etc/crontabs/root" ] || [ $(cat /etc/crontabs/root | grep "$cmd" | wc -l) -eq 0 ]; then
			sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
			echo "$cmd" >> /etc/crontabs/root
		fi
	fi
	if [ $dstype = 1 ] ; then
		local cmd="$minute $hour * * $week sleep 5 && touch /etc/banner && poweroff" 
		if [ ! -f "/etc/crontabs/root" ] || [ $(cat /etc/crontabs/root | grep "$cmd" | wc -l) -eq 0 ]; then
			sed -i '/poweroff/d' /etc/crontabs/root >/dev/null 2>&1
			echo "$cmd" >> /etc/crontabs/root
		fi
	fi
		
}

start()
{
	local enabled=$(uci get autopoweroff.@login[0].enabled)
	[ "$enabled" -eq 0 ] && exit
	config_load autopoweroff
	config_foreach run_poweroff autopoweroff
}

del_cru()
{
	if [ -f "/etc/crontabs/root" ] && [ $(cat /etc/crontabs/root | grep reboot | wc -l) -ne 0 ]; then
		sed -i '/reboot/d' /etc/crontabs/root >/dev/null 2>&1
	fi
	if [ -f "/etc/crontabs/root" ] && [ $(cat /etc/crontabs/root | grep poweroff | wc -l) -ne 0 ]; then
		sed -i '/poweroff/d' /etc/crontabs/root >/dev/null 2>&1
	fi
}

stop() {
	del_cru
}

restart(){
	stop
	start
}