
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for misc configure
LUCI_PKGARCH:=all
PKG_VERSION:=1.4
PKG_RELEASE:=2

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
