#!/bin/sh
chmod +x /etc/init.d/wizard 2>/dev/null
[ "x$(uci -q get wizard.default.display)" = "x1"  ] &&  echo ' ' > /etc/config/wizarded || rm -rf /etc/config/wizarded
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@wizard[-1]
	add ucitrack wizard
	set ucitrack.@wizard[-1].init=wizard
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
