#
# Copyright (C) 2020 OpenWrt.org
# 流量统计
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

PKG_NAME:=wrtbwmon
PKG_VERSION:=v0.3
PKG_RELEASE:=1
LUCI_TITLE:=Wrtbwmon

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
