#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autotimeset[-1]
	add ucitrack autotimeset
	set ucitrack.@autotimeset[-1].init=autotimeset
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
