#
#-- Copyright (C) 2018 dz <bauw2008@163.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for cupsd
LUCI_DEPENDS:= +cups +cups-bjnp +cups-dymo +cups-opfilter
PKG_VERSION:=1.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
