#!/bin/sh
[ -s /etc/config/netwizard ] || echo "config netwizard default" > /etc/config/netwizard
IPADDR=` uci get network.lan.ipaddr 2>/dev/null` 
[ "$(uci -q get network.wan.proto)" ] && uci -q set netwizard.default.wan_proto=` uci -q get network.wan.proto  || echo "siderouter" ` 
uci -q set netwizard.default.lan_ipaddr="${IPADDR}"
uci -q set netwizard.default.lan_netmask=` uci -q get network.lan.netmask `
uci -q set netwizard.default.lan_gateway="${IPADDR%.*}"
uci commit netwizard 
rm -f /tmp/luci*
exit 0
