#!/bin/sh
chmod +x /etc/init.d/netwizard 2>/dev/null

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netwizard[-1]
	add ucitrack netwizard
	set ucitrack.@netwizard[-1].init="netwizard"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
