#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021-2022  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/luci-app-lucky 
#
# This file is part of lucky .
# 
# This is free software, licensed under the Apache License, Version 2.0 .
#


START=99
USE_PROCD=1

PROG=/usr/bin/lucky
CONFDIR=/etc/lucky
CONF=/etc/lucky/lucky.conf

get_config() {
        config_get_bool enabled $1 enabled 1
	config_get_bool logger $1 logger 1
	config_get port $1 port 16601
}
lucky_prepare() {
	pgrep -f /usr/bin/lucky | xargs kill -9 >/dev/null 2>&1 
	logger -t lucky -p warn "lucky is stop."
}

init_conf(){
	[ -d $CONFDIR ] || mkdir -p $CONFDIR 2>/dev/null
	[ -s ${CONF}/lucky-default.conf ]  && cp -r $CONFDIR/lucky-default.conf $CONF || return 1
}

stop_service() {
	lucky_prepare
}

start_service() {
	lucky_prepare
	config_load lucky
        config_foreach get_config lucky
	[ x$enabled == x1 ] || return 1
	[ -s ${CONF} ] || init_conf
	sed -i "s/16601/$port/g" "$CONF"
	logger -t lucky -p warn "lucky is start."
	echo "lucky is start."
	procd_open_instance
	procd_set_param command $PROG -c "$CONF" -p $port
	[ "x$logger" == x1 ] && procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
      procd_add_reload_trigger "lucky"
}
