#!/bin/sh

mem="$(awk '/^MemTotal:/ {print $2}' /proc/meminfo)"

if [ "$mem" -gt 131072 ]; then # mem > 128M 
	disk_cache='16M'
elif [ "$mem" -gt 65536 ]; then # 64M < mem <= 128M
	disk_cache='8M'
elif [ "$mem" -gt 32768 ]; then # 32M < mem <= 64M
	disk_cache='2M'
else
	disk_cache='1M'
fi

uci -q set aria2.main.disk_cache="$disk_cache"
uci commit aria2

exit 0
