#!/bin/sh
touch /etc/config/dns-to
# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@dns-to[-1]
	add ucitrack dns-to
	set ucitrack.@dns-to[-1].init=dns-to
	commit ucitrack
EOF
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
