

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-homeassistant
PKG_VERSION:=1.0.1
PKG_RELEASE:=20210923

LUCI_TITLE:=LuCI support for homeassistant
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+docker

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature


