#!/bin/sh /etc/rc.common
# Copyright 2020 -2021 sirpdboy (herboy2008@gmail.com)

START=95
STOP=10

. /lib/functions.sh
EXTRA_COMMANDS="nstest"
EXTRA_HELP="	netspeedtest"
NS_FILE=/usr/share/netspeedtest/netspeedtest.txt
TMP_T=/tmp/netspeedtest
LOG="/var/log/netspeedtest.log"

limit_log() {
	local logf=$1
	[ ! -f "$logf" ] && return
	local sc=100
	[ -n "$2" ] && sc=$2
	local count=$(grep -c "" $logf)
	if [ $count -gt $sc ];then
		let count=count-$sc
		sed -i "1,$count d" $logf
	fi
}


boot() {
	XBOOT=1 start
}

init_env() {
	[ ! -f "$LOG" ] && echo "" > $LOG
	echo 1 > $TMP_T
   
}

nstest() {
[ "x$XBOOT" = "x1" ] && return 0
    init_env
    echo -ne "\n  ————————————————————————————" | tee -a $LOG
    /usr/sbin/speedtest   --no-upload  | tee -a $TMP_T
	 echo -ne  "\n  测服信息:$(cat  $TMP_T | grep 'Hosted by'| cut -c10- | awk -F: '{printf $1}')  延时：$(cat  $TMP_T | grep 'Hosted by' | awk -F: '{printf $2}')" | tee -a $LOG
        echo -ne "\n  下行速率:$(cat  $TMP_T  | grep 'Download:' |awk -F: '{printf $2}' )"   | tee -a $LOG

    /usr/sbin/speedtest   --no-download  | tee -a $TMP_T
    echo -ne "   ---- 上行速率:$(cat  $TMP_T  | grep 'Upload:' |awk -F: '{printf $2}' )"  | tee -a $LOG
	echo -ne "\n  测试时间: " | tee -a $LOG
	echo $(date +%Y-%m-%d" "%H:%M:%S) | tee -a $LOG
	rm -rf $TMP_T
}

reload(){
 	start
}

start() {
    limit_log $LOG 200
	nstest
}
restart() {
	XRELOAD=1 start
}