#
# Copyright (C) 2024
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for vusb
LUCI_DEPENDS:=+vusb
LUCI_PKGARCH:=all

PKG_MAINTAINER:=bauw

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
